# Generated by Django 4.2.21 on 2025-05-20 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosa',
            old_name='deskripsi',
            new_name='solusi',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='gejala',
        ),
        migrations.AddField(
            model_name='rule',
            name='gejala_ids',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosa',
            name='kode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnosa',
            name='nama',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gejala',
            name='kode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gejala',
            name='nama',
            field=models.TextField(),
        ),
    ]
